# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/291/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /snap/clion/291/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/monika/cpp/ecosystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/monika/cpp/ecosystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/snap/clion/291/bin/cmake/linux/x64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/clion/291/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/monika/cpp/ecosystem/CMakeFiles /home/monika/cpp/ecosystem//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/monika/cpp/ecosystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ecosystem

# Build rule for target.
ecosystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecosystem
.PHONY : ecosystem

# fast build rule for target.
ecosystem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/build
.PHONY : ecosystem/fast

#=============================================================================
# Target rules for targets named ecosystem_autogen_timestamp_deps

# Build rule for target.
ecosystem_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecosystem_autogen_timestamp_deps
.PHONY : ecosystem_autogen_timestamp_deps

# fast build rule for target.
ecosystem_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem_autogen_timestamp_deps.dir/build.make CMakeFiles/ecosystem_autogen_timestamp_deps.dir/build
.PHONY : ecosystem_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ecosystem_autogen

# Build rule for target.
ecosystem_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecosystem_autogen
.PHONY : ecosystem_autogen

# fast build rule for target.
ecosystem_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem_autogen.dir/build.make CMakeFiles/ecosystem_autogen.dir/build
.PHONY : ecosystem_autogen/fast

ecosystem_autogen/mocs_compilation.o: ecosystem_autogen/mocs_compilation.cpp.o
.PHONY : ecosystem_autogen/mocs_compilation.o

# target to build an object file
ecosystem_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/ecosystem_autogen/mocs_compilation.cpp.o
.PHONY : ecosystem_autogen/mocs_compilation.cpp.o

ecosystem_autogen/mocs_compilation.i: ecosystem_autogen/mocs_compilation.cpp.i
.PHONY : ecosystem_autogen/mocs_compilation.i

# target to preprocess a source file
ecosystem_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/ecosystem_autogen/mocs_compilation.cpp.i
.PHONY : ecosystem_autogen/mocs_compilation.cpp.i

ecosystem_autogen/mocs_compilation.s: ecosystem_autogen/mocs_compilation.cpp.s
.PHONY : ecosystem_autogen/mocs_compilation.s

# target to generate assembly for a file
ecosystem_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/ecosystem_autogen/mocs_compilation.cpp.s
.PHONY : ecosystem_autogen/mocs_compilation.cpp.s

gui/InteractiveOrganism.o: gui/InteractiveOrganism.cpp.o
.PHONY : gui/InteractiveOrganism.o

# target to build an object file
gui/InteractiveOrganism.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/gui/InteractiveOrganism.cpp.o
.PHONY : gui/InteractiveOrganism.cpp.o

gui/InteractiveOrganism.i: gui/InteractiveOrganism.cpp.i
.PHONY : gui/InteractiveOrganism.i

# target to preprocess a source file
gui/InteractiveOrganism.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/gui/InteractiveOrganism.cpp.i
.PHONY : gui/InteractiveOrganism.cpp.i

gui/InteractiveOrganism.s: gui/InteractiveOrganism.cpp.s
.PHONY : gui/InteractiveOrganism.s

# target to generate assembly for a file
gui/InteractiveOrganism.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/gui/InteractiveOrganism.cpp.s
.PHONY : gui/InteractiveOrganism.cpp.s

gui/MainWindow.o: gui/MainWindow.cpp.o
.PHONY : gui/MainWindow.o

# target to build an object file
gui/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/gui/MainWindow.cpp.o
.PHONY : gui/MainWindow.cpp.o

gui/MainWindow.i: gui/MainWindow.cpp.i
.PHONY : gui/MainWindow.i

# target to preprocess a source file
gui/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/gui/MainWindow.cpp.i
.PHONY : gui/MainWindow.cpp.i

gui/MainWindow.s: gui/MainWindow.cpp.s
.PHONY : gui/MainWindow.s

# target to generate assembly for a file
gui/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/gui/MainWindow.cpp.s
.PHONY : gui/MainWindow.cpp.s

gui/moc_MainWindow.o: gui/moc_MainWindow.cpp.o
.PHONY : gui/moc_MainWindow.o

# target to build an object file
gui/moc_MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/gui/moc_MainWindow.cpp.o
.PHONY : gui/moc_MainWindow.cpp.o

gui/moc_MainWindow.i: gui/moc_MainWindow.cpp.i
.PHONY : gui/moc_MainWindow.i

# target to preprocess a source file
gui/moc_MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/gui/moc_MainWindow.cpp.i
.PHONY : gui/moc_MainWindow.cpp.i

gui/moc_MainWindow.s: gui/moc_MainWindow.cpp.s
.PHONY : gui/moc_MainWindow.s

# target to generate assembly for a file
gui/moc_MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/gui/moc_MainWindow.cpp.s
.PHONY : gui/moc_MainWindow.cpp.s

include/moc_Reserve.o: include/moc_Reserve.cpp.o
.PHONY : include/moc_Reserve.o

# target to build an object file
include/moc_Reserve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/include/moc_Reserve.cpp.o
.PHONY : include/moc_Reserve.cpp.o

include/moc_Reserve.i: include/moc_Reserve.cpp.i
.PHONY : include/moc_Reserve.i

# target to preprocess a source file
include/moc_Reserve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/include/moc_Reserve.cpp.i
.PHONY : include/moc_Reserve.cpp.i

include/moc_Reserve.s: include/moc_Reserve.cpp.s
.PHONY : include/moc_Reserve.s

# target to generate assembly for a file
include/moc_Reserve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/include/moc_Reserve.cpp.s
.PHONY : include/moc_Reserve.cpp.s

include/moc_SimulationThread.o: include/moc_SimulationThread.cpp.o
.PHONY : include/moc_SimulationThread.o

# target to build an object file
include/moc_SimulationThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/include/moc_SimulationThread.cpp.o
.PHONY : include/moc_SimulationThread.cpp.o

include/moc_SimulationThread.i: include/moc_SimulationThread.cpp.i
.PHONY : include/moc_SimulationThread.i

# target to preprocess a source file
include/moc_SimulationThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/include/moc_SimulationThread.cpp.i
.PHONY : include/moc_SimulationThread.cpp.i

include/moc_SimulationThread.s: include/moc_SimulationThread.cpp.s
.PHONY : include/moc_SimulationThread.s

# target to generate assembly for a file
include/moc_SimulationThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/include/moc_SimulationThread.cpp.s
.PHONY : include/moc_SimulationThread.cpp.s

qrc_resources.o: qrc_resources.cpp.o
.PHONY : qrc_resources.o

# target to build an object file
qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/qrc_resources.cpp.o
.PHONY : qrc_resources.cpp.o

qrc_resources.i: qrc_resources.cpp.i
.PHONY : qrc_resources.i

# target to preprocess a source file
qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/qrc_resources.cpp.i
.PHONY : qrc_resources.cpp.i

qrc_resources.s: qrc_resources.cpp.s
.PHONY : qrc_resources.s

# target to generate assembly for a file
qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/qrc_resources.cpp.s
.PHONY : qrc_resources.cpp.s

src/Carnivore.o: src/Carnivore.cpp.o
.PHONY : src/Carnivore.o

# target to build an object file
src/Carnivore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Carnivore.cpp.o
.PHONY : src/Carnivore.cpp.o

src/Carnivore.i: src/Carnivore.cpp.i
.PHONY : src/Carnivore.i

# target to preprocess a source file
src/Carnivore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Carnivore.cpp.i
.PHONY : src/Carnivore.cpp.i

src/Carnivore.s: src/Carnivore.cpp.s
.PHONY : src/Carnivore.s

# target to generate assembly for a file
src/Carnivore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Carnivore.cpp.s
.PHONY : src/Carnivore.cpp.s

src/Herbivore.o: src/Herbivore.cpp.o
.PHONY : src/Herbivore.o

# target to build an object file
src/Herbivore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Herbivore.cpp.o
.PHONY : src/Herbivore.cpp.o

src/Herbivore.i: src/Herbivore.cpp.i
.PHONY : src/Herbivore.i

# target to preprocess a source file
src/Herbivore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Herbivore.cpp.i
.PHONY : src/Herbivore.cpp.i

src/Herbivore.s: src/Herbivore.cpp.s
.PHONY : src/Herbivore.s

# target to generate assembly for a file
src/Herbivore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Herbivore.cpp.s
.PHONY : src/Herbivore.cpp.s

src/Organism.o: src/Organism.cpp.o
.PHONY : src/Organism.o

# target to build an object file
src/Organism.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Organism.cpp.o
.PHONY : src/Organism.cpp.o

src/Organism.i: src/Organism.cpp.i
.PHONY : src/Organism.i

# target to preprocess a source file
src/Organism.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Organism.cpp.i
.PHONY : src/Organism.cpp.i

src/Organism.s: src/Organism.cpp.s
.PHONY : src/Organism.s

# target to generate assembly for a file
src/Organism.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Organism.cpp.s
.PHONY : src/Organism.cpp.s

src/Plant.o: src/Plant.cpp.o
.PHONY : src/Plant.o

# target to build an object file
src/Plant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Plant.cpp.o
.PHONY : src/Plant.cpp.o

src/Plant.i: src/Plant.cpp.i
.PHONY : src/Plant.i

# target to preprocess a source file
src/Plant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Plant.cpp.i
.PHONY : src/Plant.cpp.i

src/Plant.s: src/Plant.cpp.s
.PHONY : src/Plant.s

# target to generate assembly for a file
src/Plant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Plant.cpp.s
.PHONY : src/Plant.cpp.s

src/PoisonousPlant.o: src/PoisonousPlant.cpp.o
.PHONY : src/PoisonousPlant.o

# target to build an object file
src/PoisonousPlant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/PoisonousPlant.cpp.o
.PHONY : src/PoisonousPlant.cpp.o

src/PoisonousPlant.i: src/PoisonousPlant.cpp.i
.PHONY : src/PoisonousPlant.i

# target to preprocess a source file
src/PoisonousPlant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/PoisonousPlant.cpp.i
.PHONY : src/PoisonousPlant.cpp.i

src/PoisonousPlant.s: src/PoisonousPlant.cpp.s
.PHONY : src/PoisonousPlant.s

# target to generate assembly for a file
src/PoisonousPlant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/PoisonousPlant.cpp.s
.PHONY : src/PoisonousPlant.cpp.s

src/Reserve.o: src/Reserve.cpp.o
.PHONY : src/Reserve.o

# target to build an object file
src/Reserve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Reserve.cpp.o
.PHONY : src/Reserve.cpp.o

src/Reserve.i: src/Reserve.cpp.i
.PHONY : src/Reserve.i

# target to preprocess a source file
src/Reserve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Reserve.cpp.i
.PHONY : src/Reserve.cpp.i

src/Reserve.s: src/Reserve.cpp.s
.PHONY : src/Reserve.s

# target to generate assembly for a file
src/Reserve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/Reserve.cpp.s
.PHONY : src/Reserve.cpp.s

src/SimulationController.o: src/SimulationController.cpp.o
.PHONY : src/SimulationController.o

# target to build an object file
src/SimulationController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/SimulationController.cpp.o
.PHONY : src/SimulationController.cpp.o

src/SimulationController.i: src/SimulationController.cpp.i
.PHONY : src/SimulationController.i

# target to preprocess a source file
src/SimulationController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/SimulationController.cpp.i
.PHONY : src/SimulationController.cpp.i

src/SimulationController.s: src/SimulationController.cpp.s
.PHONY : src/SimulationController.s

# target to generate assembly for a file
src/SimulationController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/SimulationController.cpp.s
.PHONY : src/SimulationController.cpp.s

src/SimulationThread.o: src/SimulationThread.cpp.o
.PHONY : src/SimulationThread.o

# target to build an object file
src/SimulationThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/SimulationThread.cpp.o
.PHONY : src/SimulationThread.cpp.o

src/SimulationThread.i: src/SimulationThread.cpp.i
.PHONY : src/SimulationThread.i

# target to preprocess a source file
src/SimulationThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/SimulationThread.cpp.i
.PHONY : src/SimulationThread.cpp.i

src/SimulationThread.s: src/SimulationThread.cpp.s
.PHONY : src/SimulationThread.s

# target to generate assembly for a file
src/SimulationThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/SimulationThread.cpp.s
.PHONY : src/SimulationThread.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecosystem.dir/build.make CMakeFiles/ecosystem.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ecosystem_autogen"
	@echo "... ecosystem_autogen_timestamp_deps"
	@echo "... ecosystem"
	@echo "... ecosystem_autogen/mocs_compilation.o"
	@echo "... ecosystem_autogen/mocs_compilation.i"
	@echo "... ecosystem_autogen/mocs_compilation.s"
	@echo "... gui/InteractiveOrganism.o"
	@echo "... gui/InteractiveOrganism.i"
	@echo "... gui/InteractiveOrganism.s"
	@echo "... gui/MainWindow.o"
	@echo "... gui/MainWindow.i"
	@echo "... gui/MainWindow.s"
	@echo "... gui/moc_MainWindow.o"
	@echo "... gui/moc_MainWindow.i"
	@echo "... gui/moc_MainWindow.s"
	@echo "... include/moc_Reserve.o"
	@echo "... include/moc_Reserve.i"
	@echo "... include/moc_Reserve.s"
	@echo "... include/moc_SimulationThread.o"
	@echo "... include/moc_SimulationThread.i"
	@echo "... include/moc_SimulationThread.s"
	@echo "... qrc_resources.o"
	@echo "... qrc_resources.i"
	@echo "... qrc_resources.s"
	@echo "... src/Carnivore.o"
	@echo "... src/Carnivore.i"
	@echo "... src/Carnivore.s"
	@echo "... src/Herbivore.o"
	@echo "... src/Herbivore.i"
	@echo "... src/Herbivore.s"
	@echo "... src/Organism.o"
	@echo "... src/Organism.i"
	@echo "... src/Organism.s"
	@echo "... src/Plant.o"
	@echo "... src/Plant.i"
	@echo "... src/Plant.s"
	@echo "... src/PoisonousPlant.o"
	@echo "... src/PoisonousPlant.i"
	@echo "... src/PoisonousPlant.s"
	@echo "... src/Reserve.o"
	@echo "... src/Reserve.i"
	@echo "... src/Reserve.s"
	@echo "... src/SimulationController.o"
	@echo "... src/SimulationController.i"
	@echo "... src/SimulationController.s"
	@echo "... src/SimulationThread.o"
	@echo "... src/SimulationThread.i"
	@echo "... src/SimulationThread.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

